replicaCount: 2

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

service:
  type: NodePort
  port: 8000
  nodePort: 30081

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

