name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      name: Checkout Code
      uses: actions/checkout@v5
    
      name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'