name: Terraform AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action: apply or destroy"
        required: true
        default: "apply"
      confirm:
        description: "Confirm your choice again"
        required: true
        default: "none"

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.2

      - name: Verify double confirmation
        run: |
          if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            if [ "${{ github.event.inputs.confirm }}" != "apply" ]; then
              echo "Confirmation failed: you must type 'apply' to proceed."
              exit 1
            fi
          elif [ "${{ github.event.inputs.action }}" = "destroy" ]; then
            if [ "${{ github.event.inputs.confirm }}" != "destroy" ]; then
              echo "Confirmation failed: you must type 'destroy' to proceed."
              exit 1
            fi
          else
            echo "Invalid action input. Must be 'apply' or 'destroy'."
            exit 1
          fi

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        if: github.event.inputs.action == 'apply'
        working-directory: terraform
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: terraform
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: terraform
        run: terraform destroy -auto-approve
